тест передачи вывода в переменную и в другую команду вар7

diff --git a/.github/workflows/CI_CD_DO5_project.yml b/.github/workflows/CI_CD_DO5_project.yml
--- a/.github/workflows/CI_CD_DO5_project.yml
+++ b/.github/workflows/CI_CD_DO5_project.yml
@@ -1,4 +1,3 @@
-name: "CI_CD for DO5_Simple_docker Project"
 
 on:
   push:
@@ -24,8 +23,6 @@ jobs:
         run: |
           output=$(docker ps -q)
           docker inspect $output
-         # echo $output >> $GITHUB_ENV
-         # docker inspect ${{ env.output }}
           docker stop $output
           if docker ps -q | grep $output; then
             echo "Container in use. Exiting with error."
@@ -34,8 +31,17 @@ jobs:
             echo "OK"
           fi
 
-      - name: Docker_whith_ports
-        run: docker -d -p 80:80 -p 443:443 nginx
+      - name: Check if port 80 is in use
+        run: |
+          if fuser -k 80/tcp; then
+            echo "Port 80 is in use. Exiting with error."
+            exit 1
+          else
+            echo "Port 80 is not in use."
+          fi
+
+      - name: Docker_with_ports  
+        run: docker run -d -p 80:80 -p 443:443 nginx 
 
       - name: Postman_test
         working-directory: DO5_SimpleDocker-1-develop/src/01/
